name: 'beta-merge'

on:
  push:
    branches:
    - beta

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          ref: beta
          
      - name: Create .env
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_VITE_KAKAO_API_KEY: ${{ secrets.VITE_KAKAO_API_KEY }}
          file_name: .env

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Versioning
        run: yarn release
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-dist
          path: ./dist
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build-dist
          
      - name: Upload to S3  
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2
          AWS_S3: ${{ secrets.BETA_DEPLOY_AWS_S3 }}
        run: |
          aws s3 sync --region ap-northeast-2 ./ $AWS_S3 --follow-symlinks --delete
      
      - name: Invalidate CloudFront Cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2
          AWS_CLOUDFRONT_ID: ${{ secrets.BETA_DEPLOY_CLOUDFRONT_ID }}
        run: |
          aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_ID --paths "/*"